fix test_rest_server
Applied patch provided by @OGAWAHirofumi - thanks a lot!

Comment:

Looks like the response context affects the latter context sometimes.
Specifically, looks like the client.head() context affected client.get().

  AssertionError: Popped wrong request context. (<RequestContext 'http://localhost/apis/rest/items/PdL9Js9f/download' [GET] of bepasty.app> instead of <RequestContext 'http://localhost/apis/rest/items/PdL9Js9f/download' [HEAD] of bepasty.app>)

Like the above error ("HEAD" context got in "GET" context).  I don't
know whether this is a flask bug, but it can be prevented by calling
.close() for the response (or using the context manager via "with").